# ==============================================================================
# Tool Explanations — used by --explain flag and 'eN' menu prefix
# ==============================================================================

_explain_tool() {
    local tool_name="$1"

    echo ""
    echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"

    case $tool_name in

        # ──────────────────────────────────────────────────────────────
        # BROWSERS
        # ──────────────────────────────────────────────────────────────
        Brave)
            echo -e "${YELLOW}Brave Browser${NC}"
            echo ""
            echo "Privacy-focused Chromium-based browser with built-in ad/tracker blocking."
            echo ""
            echo "Tips:"
            echo "  • Built-in Brave Shields block ads, trackers, and fingerprinting"
            echo "  • Brave Rewards lets you earn BAT for viewing privacy-respecting ads"
            echo "  • Supports all Chrome extensions via the Chrome Web Store"
            echo "  • Has built-in Tor browsing in private windows"
            echo "  • Syncs bookmarks/passwords across devices without an account"
            ;;
        "Google Chrome")
            echo -e "${YELLOW}Google Chrome${NC}"
            echo ""
            echo "Most widely-used web browser, built on Chromium."
            echo ""
            echo "Tips:"
            echo "  • Best-in-class DevTools for web development"
            echo "  • Chrome Remote Desktop for accessing other machines"
            echo "  • Cast tab/desktop to Chromecast devices"
            echo "  • Profile system for separating work/personal browsing"
            echo "  • Memory Saver frees RAM from inactive tabs"
            ;;
        Firefox)
            echo -e "${YELLOW}Firefox${NC}"
            echo ""
            echo "Open-source browser from Mozilla, focused on privacy and standards."
            echo ""
            echo "Tips:"
            echo "  • about:config — advanced settings (use with care)"
            echo "  • Enhanced Tracking Protection blocks trackers by default"
            echo "  • Firefox Multi-Account Containers isolate sites (work/personal)"
            echo "  • Pocket integration for saving articles offline"
            echo "  • Developer Edition available alongside this install"
            ;;
        Vivaldi)
            echo -e "${YELLOW}Vivaldi${NC}"
            echo ""
            echo "Feature-rich browser built for power users, by former Opera devs."
            echo ""
            echo "Tips:"
            echo "  • Highly customizable UI — move tabs, change themes, keyboard shortcuts"
            echo "  • Built-in notes, screenshot tool, and calendar"
            echo "  • Tab stacking and tiling for organizing many tabs"
            echo "  • Command Chain — run multiple actions from one keyboard shortcut"
            echo "  • Workspaces let you switch between sets of tabs for different contexts"
            ;;
        Chromium)
            echo -e "${YELLOW}Chromium${NC}"
            echo ""
            echo "Open-source base of Chrome, without Google branding or services."
            echo ""
            echo "Tips:"
            echo "  • No built-in sync, DRM (Widevine), or auto-updater"
            echo "  • Can install Widevine manually for Netflix/Spotify"
            echo "  • Lightweight alternative to Chrome for developers"
            echo "  • Flags at chrome://flags — experimental features"
            ;;
        "Firefox Developer Edition")
            echo -e "${YELLOW}Firefox Developer Edition${NC}"
            echo ""
            echo "Firefox build tailored for web developers."
            echo ""
            echo "Tips:"
            echo "  • Separate profile from regular Firefox — run both side-by-side"
            echo "  • Includes Firefox DevTools with advanced grid/flexbox inspectors"
            echo "  • Enabled by default: console.log styling, source maps, WebIDE"
            echo "  • Gets feature updates before standard Firefox"
            echo "  • Has a dark theme designed for developers"
            ;;
        "Ungoogled Chromium")
            echo -e "${YELLOW}Ungoogled Chromium${NC}"
            echo ""
            echo "Chromium with Google services, web dependencies, and blobs removed."
            echo ""
            echo "Tips:"
            echo "  • Maximum privacy — no Google API calls, safe browsing, or crash reporting"
            echo "  • Some sites may break (reCAPTCHA, Google services, etc.)"
            echo "  • Add Widevine manually for DRM content"
            echo "  • Install via Flatpak for sandboxed updates"
            echo "  • Good choice if you want Chromium without any Google telemetry"
            ;;
        LibreWolf)
            echo -e "${YELLOW}LibreWolf${NC}"
            echo ""
            echo "Privacy-hardened Firefox fork with telemetry disabled and enhanced tracking protection."
            echo ""
            echo "Tips:"
            echo "  • uBlock Origin pre-installed and configured"
            echo "  • Can't use Mozilla sync (intentionally disabled)"
            echo "  • Uses its own profile, can run alongside Firefox"
            echo "  • Auto-updates via package manager (not built-in)"
            echo "  • Good out-of-the-box privacy without configuring about:config"
            ;;

        # ──────────────────────────────────────────────────────────────
        # UTILITIES
        # ──────────────────────────────────────────────────────────────
        Obsidian)
            echo -e "${YELLOW}Obsidian${NC}"
            echo ""
            echo "Local-first knowledge base and Markdown note-taking app."
            echo ""
            echo "Tips:"
            echo "  • All notes are plain Markdown files on your filesystem"
            echo "  • Graph View shows connections between linked notes"
            echo "  • Community plugins extend functionality (Kanban, Calendar, Excalidraw)"
            echo "  • Use [[wikilinks]] to connect notes together"
            echo "  • Sync across devices via Obsidian Sync (paid) or a cloud folder (free)"
            ;;
        "WPS Office")
            echo -e "${YELLOW}WPS Office${NC}"
            echo ""
            echo "Full-featured office suite (Writer, Spreadsheets, Presentation), Microsoft Office-compatible."
            echo ""
            echo "Tips:"
            echo "  • Free version includes ads, which can be removed in settings"
            echo "  • Better Microsoft Office file compatibility than LibreOffice in many cases"
            echo "  • Supports PDF editing and conversion"
            echo "  • Cloud storage integration with multiple providers"
            echo "  • Tabbed document interface by default"
            ;;
        "OBS Studio")
            echo -e "${YELLOW}OBS Studio${NC}"
            echo ""
            echo "Open-source software for video recording and live streaming."
            echo ""
            echo "Tips:"
            echo "  • Scene system: combine sources (window, screen, camera, audio) into scenes"
            echo "  • Hotkey setup: Settings → Hotkeys for start/stop recording/streaming"
            echo "  • Browser overlay sources for stream alerts and widgets"
            echo "  • Use 'Replay Buffer' to save last N seconds of gameplay"
            ;;
        ffmpeg)
            echo -e "${YELLOW}ffmpeg${NC}"
            echo ""
            echo "Universal multimedia converter — the swiss army knife of audio/video."
            echo ""
            echo "Common flags:"
            echo "  ffmpeg -i input.mp4 output.mp3          Convert video to audio"
            echo "  ffmpeg -i input.mp4 -vf scale=1280:720 output.mp4   Resize video"
            echo "  ffmpeg -i input.mp4 -ss 00:01:30 -t 10 clip.mp4     Cut 10s clip at 1m30s"
            echo "  ffmpeg -i input.mp4 -c:v libx265 output.mp4         Encode in H.265/HEVC"
            echo "  ffmpeg -i input.mp4 -an output.mp4                  Remove audio track"
            echo "  ffprobe input.mp4                      Show media metadata"
            echo ""
            echo "Codecs: -c:v libx264 (H.264), libx265 (HEVC), libvpx-vp9 (VP9)"
            echo "Flags:  -crf 23 (quality 0-51, lower=better), -preset medium (speed)"
            ;;
        yt-dlp)
            echo -e "${YELLOW}yt-dlp${NC}"
            echo ""
            echo "Feature-rich YouTube/website video downloader (fork of youtube-dl)."
            echo ""
            echo "Common flags:"
            echo "  yt-dlp 'URL'                           Download best quality"
            echo "  yt-dlp -f 'bestvideo+bestaudio' 'URL'  Best video+audio separately"
            echo "  yt-dlp -x --audio-format mp3 'URL'     Extract audio only"
            echo "  yt-dlp -o '%(title)s.%(ext)s' 'URL'    Custom output filename"
            echo "  yt-dlp --playlist-start 1 --playlist-end 5 'URL'  Download playlist range"
            echo "  yt-dlp -S 'res:1080' 'URL'             Filter by resolution"
            echo "  yt-dlp --cookies-from-browser firefox 'URL'  Use browser cookies"
            ;;
        "VS Code")
            echo -e "${YELLOW}Visual Studio Code${NC}"
            echo ""
            echo "Lightweight but powerful source code editor from Microsoft."
            echo ""
            echo "Tips:"
            echo "  • Ctrl+Shift+X — extensions marketplace"
            echo "  • Ctrl+Shift+P — command palette (access any action)"
            echo "  • Ctrl+P — quick file open (fuzzy search)"
            echo "  • Integrated terminal: Ctrl+\` "
            echo "  • Settings Sync via GitHub account"
            echo "  • Multi-cursor: Alt+click (or Ctrl+Alt+Up/Down)"
            echo "  • Built-in Git integration with diff editor"
            ;;
        "Sublime Text")
            echo -e "${YELLOW}Sublime Text${NC}"
            echo ""
            echo "Fast, minimalist text editor with powerful editing features."
            echo ""
            echo "Tips:"
            echo "  • Ctrl+P — Goto Anything (files, symbols, lines)"
            echo "  • Ctrl+D — select next occurrence of current word"
            echo "  • Ctrl+Shift+L — split selection into lines"
            echo "  • Package Control (install via Ctrl+Shift+P → Install Package Control)"
            echo "  • Multiple cursors: Ctrl+click, Ctrl+D, or Alt+F3"
            echo "  • Vintage mode for Vim keybindings"
            ;;
        "JetBrains Toolbox")
            echo -e "${YELLOW}JetBrains Toolbox${NC}"
            echo ""
            echo "Centralized manager for all JetBrains IDEs (IntelliJ, PyCharm, GoLand, etc.)."
            echo ""
            echo "Tips:"
            echo "  • Install and update all JetBrains tools from one place"
            echo "  • Each IDE stays in its own versioned directory — safe to rollback"
            echo "  • Project quick-launch from the Toolbox widget"
            echo "  • Shell scripts for each IDE are added to PATH automatically"
            ;;

        # ──────────────────────────────────────────────────────────────
        # TERMINALS
        # ──────────────────────────────────────────────────────────────
        Kitty)
            echo -e "${YELLOW}Kitty${NC}"
            echo ""
            echo "GPU-accelerated terminal emulator with great performance and features."
            echo ""
            echo "Tips:"
            echo "  • Config file: ~/.config/kitty/kitty.conf"
            echo "  • Ctrl+Shift+T — new tab; Ctrl+Shift+N — new window"
            echo "  • Images displayed inline via icat (kitty +kitten icat image.png)"
            echo "  • Built-in Unicode/Ligature support"
            echo "  • Remote file editing: kitty +kitten ssh user@host"
            echo "  • Extremely configurable keyboard shortcuts"
            ;;
        Alacritty)
            echo -e "${YELLOW}Alacritty${NC}"
            echo ""
            echo "GPU-accelerated terminal emulator focused on simplicity and performance."
            echo ""
            echo "Tips:"
            echo "  • Config file: ~/.config/alacritty/alacritty.toml"
            echo "  • No tabs or splits — pair with tmux for that"
            echo "  • Vi mode: Ctrl+Shift+Space → navigate with h/j/k/l, yank with y"
            echo "  • True color and ligatures supported"
            echo "  • Extremely fast rendering"
            ;;
        Tilix)
            echo -e "${YELLOW}Tilix${NC}"
            echo ""
            echo "Feature-rich GTK3 terminal emulator with tiling layout."
            echo ""
            echo "Tips:"
            echo "  • Built-in split panes (horizontal and vertical)"
            echo "  • Save/restore session layouts"
            echo "  • Drag-and-drop terminal groups into splits"
            echo "  • Customizable notifications for process completion"
            echo "  • Supports transparent backgrounds and image backgrounds"
            echo "  • Integrated with GNOME desktop theming"
            ;;
        "GNOME Terminal")
            echo -e "${YELLOW}GNOME Terminal${NC}"
            echo ""
            echo "Default terminal for GNOME desktop — simple and reliable."
            echo ""
            echo "Tips:"
            echo "  • Profiles: Edit → Preferences to customize appearance"
            echo "  • Tabs: Ctrl+Shift+T (new), Ctrl+PageUp/PageDown (switch)"
            echo "  • Custom shortcuts for launching with specific profiles"
            echo "  • Links are clickable: Ctrl+click or just hover"
            echo "  • Supports hyperlinks (OSC 8 escape sequences)"
            ;;

        # ──────────────────────────────────────────────────────────────
        # SHELLS
        # ──────────────────────────────────────────────────────────────
        Zsh)
            echo -e "${YELLOW}Zsh${NC}"
            echo ""
            echo "Powerful shell with advanced completion, theming, and plugin support."
            echo ""
            echo "Tips:"
            echo "  • Config: ~/.zshrc"
            echo "  • Install Oh My Zsh (or zplug/antigen) for themes and plugins"
            echo "  • Powerful tab completion out of the box"
            echo "  • Globbing: **/*.txt matches recursively"
            echo "  • Prompt customization via PS1 or theme frameworks"
            ;;
        Fish)
            echo -e "${YELLOW}Fish${NC}"
            echo ""
            echo "User-friendly shell with auto-suggestions and web-based config."
            echo ""
            echo "Tips:"
            echo "  • Auto-suggestions: press → or Ctrl+F to accept"
            echo "  • Web-based config: fish_config"
            echo "  • Syntax highlighting out of the box"
            echo "  • Tab completion shows descriptions"
            echo "  • Functions defined with 'function' keyword, not Bash syntax"
            echo "  • Compatible with POSIX but uses own scripting syntax"
            ;;
        Dash)
            echo -e "${YELLOW}Dash${NC}"
            echo ""
            echo "POSIX-compliant /bin/sh — fast and minimal, ideal for scripting."
            echo ""
            echo "Tips:"
            echo "  • Used as /bin/sh on Debian/Ubuntu (faster than Bash)"
            echo "  • No interactive features — only for scripting"
            echo "  • Strict POSIX — Bash-isms will fail"
            echo "  • Great for testing script portability"
            ;;
        Ksh)
            echo -e "${YELLOW}Ksh (KornShell)${NC}"
            echo ""
            echo "Unix shell by David Korn — combines features of sh, csh, and scripting."
            echo ""
            echo "Tips:"
            echo "  • Floating-point arithmetic built-in (unlike Bash)"
            echo "  • Associative arrays before Bash had them"
            echo "  • Co-process facilities for inter-process communication"
            echo "  • Used in many legacy enterprise environments"
            ;;
        Tcsh)
            echo -e "${YELLOW}Tcsh${NC}"
            echo ""
            echo "Enhanced C shell with command-line editing and completion."
            echo ""
            echo "Tips:"
            echo "  • Scripting syntax is C-like (if, while, foreach)"
            echo "  • Used as default on some BSD systems"
            echo "  • Config: ~/.tcshrc or ~/.cshrc"
            echo "  • History substitution: !! (last), !$ (last arg)"
            ;;
        Nushell)
            echo -e "${YELLOW}Nushell${NC}"
            echo ""
            echo "Modern shell that treats everything as structured data (tables, lists)."
            echo ""
            echo "Tips:"
            echo "  • 'ls | where size > 1mb' — filter by metadata"
            echo "  • 'open file.json | select field' — query JSON natively"
            echo "  • Pipes pass structured data, not plain text"
            echo "  • Config: ~/.config/nu/config.nu"
            echo "  • Built-in data formats: JSON, CSV, TOML, YAML"
            ;;
        Elvish)
            echo -e "${YELLOW}Elvish${NC}"
            echo ""
            echo "Expressive shell with pipelines-as-functions and live reload."
            echo ""
            echo "Tips:"
            echo "  • Config: ~/.config/elvish/rc.elv"
            echo "  • Pipelines can return functions (first-class pipelines)"
            echo "  • Built-in file manager: Ctrl+N in prompt"
            echo "  • Syntax is friendly to non-POSIX backgrounds"
            echo "  • Command history navigation with Ctrl+R/Ctrl+S"
            ;;
        Xonsh)
            echo -e "${YELLOW}Xonsh${NC}"
            echo ""
            echo "Python-powered shell — mix Python and shell commands freely."
            echo ""
            echo "Tips:"
            echo "  • Python expressions evaluate directly: '2 + 2' works"
            echo "  • Capture command output: out = $(ls)"
            echo "  • Conditionals: if 'foo' in $(ls):"
            echo "  • Python virtualenv-aware out of the box"
            echo "  • Config: ~/.xonshrc (Python syntax)"
            ;;

        # ──────────────────────────────────────────────────────────────
        # AGENTIC IDEs
        # ──────────────────────────────────────────────────────────────
        OpenCode)
            echo -e "${YELLOW}OpenCode${NC}"
            echo ""
            echo "AI-native CLI coding agent that works in your terminal."
            echo ""
            echo "Tips:"
            echo "  • Operates directly on your filesystem with sudo permissions"
            echo "  • Can run terminal commands, edit files, and manage git"
            echo "  • Supports multiple AI model providers (OpenAI, Anthropic, etc.)"
            echo "  • Ideal for automated refactoring, testing, and code generation"
            ;;
        ZCode)
            echo -e "${YELLOW}ZCode${NC}"
            echo ""
            echo "AI coding assistant IDE from Z AI."
            echo ""
            echo "Tips:"
            echo "  • AI-powered code completion and chat"
            echo "  • Integrated development environment with editor"
            echo "  • Supports multiple programming languages"
            ;;
        Antigravity)
            echo -e "${YELLOW}Antigravity${NC}"
            echo ""
            echo "AI-powered development tool that automates coding workflows."
            echo ""
            echo "Tips:"
            echo "  • Automates repetitive coding tasks"
            echo "  • Integrates with existing development workflows"
            ;;
        Kiro)
            echo -e "${YELLOW}Kiro${NC}"
            echo ""
            echo "AI coding assistant from kiro.dev."
            echo ""
            echo "Tips:"
            echo "  • Code generation and explanation"
            echo "  • Available as desktop application"
            echo "  • Supports multiple programming languages and frameworks"
            ;;

        # ──────────────────────────────────────────────────────────────
        # DEV TOOLS (CLI)
        # ──────────────────────────────────────────────────────────────
        tmux)
            echo -e "${YELLOW}tmux — Terminal Multiplexer${NC}"
            echo ""
            echo "Lets you manage multiple terminal sessions, split panes, and detach/re-attach."
            echo ""
            echo "Key flags:"
            echo "  tmux new -s <name>      Start named session"
            echo "  tmux attach -t <name>   Attach to session"
            echo "  tmux ls                 List sessions"
            echo "  tmux kill-session -t <name>  Kill session"
            echo ""
            echo "Prefix: Ctrl+b, then:"
            echo "  %   Split pane vertically"
            echo '  "   Split pane horizontally'
            echo "  arrows   Navigate panes"
            echo "  c   New window"
            echo "  ,   Rename window"
            echo "  d   Detach session"
            echo "  [   Enter scroll/copy mode"
            echo "  :   Enter command mode"
            echo ""
            echo "Config: ~/.tmux.conf"
            ;;
        Neovim)
            echo -e "${YELLOW}Neovim — Modern Vim${NC}"
            echo ""
            echo "Extensible, modal text editor — a modern Vim fork with Lua API and async support."
            echo ""
            echo "Key modes:"
            echo "  Normal (Esc) — navigate, yank, delete"
            echo "  Insert (i/I/a/A/o/O) — type text"
            echo "  Visual (v/V/Ctrl+v) — select text"
            echo "  Command (:) — run commands (:w, :q, :!cmd)"
            echo ""
            echo "Essential keys:"
            echo "  h/j/k/l  — move cursor"
            echo "  w/b      — word forward/back"
            echo "  x        — delete character"
            echo "  dd       — delete line"
            echo "  yy       — yank (copy) line"
            echo "  p/P      — paste after/before"
            echo "  /<text>  — search"
            echo "  :%s/a/b/g — find & replace"
            echo "  :help    — built-in docs"
            echo ""
            echo "Config: ~/.config/nvim/init.lua"
            echo "Plugins: lazy.nvim, vim-plug"
            ;;
        Docker)
            echo -e "${YELLOW}Docker${NC}"
            echo ""
            echo "Container platform — package and run apps in isolated environments."
            echo ""
            echo "Common commands:"
            echo "  docker run -it ubuntu bash          Run interactive container"
            echo "  docker ps                           List running containers"
            echo "  docker ps -a                        List all containers"
            echo "  docker images                       List images"
            echo "  docker build -t myapp .             Build image from Dockerfile"
            echo "  docker compose up                   Start services from compose.yml"
            echo "  docker exec -it <id> bash           Shell into running container"
            echo "  docker logs -f <id>                 Follow container logs"
            echo "  docker stop <id>                    Stop container"
            echo "  docker system prune                 Clean unused data"
            ;;
        jq)
            echo -e "${YELLOW}jq — JSON Processor${NC}"
            echo ""
            echo "Command-line JSON processor — slice, filter, map, and transform JSON data."
            echo ""
            echo "Common flags:"
            echo "  jq '.key' file.json                 Extract a key"
            echo "  jq '.[] | .name' file.json          Extract from array"
            echo "  jq 'select(.age > 30)' file.json    Filter objects"
            echo "  jq -r '.key' file.json              Raw output (no quotes)"
            echo "  curl api.example.com | jq '.'       Pipe API response"
            echo "  jq '.items[] | {id, name}' file.json  Project fields"
            echo "  jq -s '.[0] * .[1]' a.json b.json   Merge files"
            ;;
        ripgrep)
            echo -e "${YELLOW}ripgrep (rg) — Fast Code Search${NC}"
            echo ""
            echo "Recursively searches directories for regex patterns — much faster than grep."
            echo ""
            echo "Key flags:"
            echo "  rg 'pattern'                        Search recursively"
            echo "  rg -i 'pattern'                     Case-insensitive"
            echo "  rg -w 'pattern'                     Whole word"
            echo "  rg -l 'pattern'                     Only list filenames"
            echo "  rg -C 3 'pattern'                   Context (3 lines before/after)"
            echo "  rg -t py 'pattern'                  File type (py, rs, js, etc.)"
            echo "  rg -g '!*.min.js' 'pattern'         Glob exclude"
            echo "  rg --no-ignore 'pattern'             Search ignored files too"
            echo "  rg 'pattern' --type-list             List known file types"
            ;;
        fzf)
            echo -e "${YELLOW}fzf — Fuzzy Finder${NC}"
            echo ""
            echo "General-purpose fuzzy finder for the command line — pipe anything in, pick one."
            echo ""
            echo "Usage patterns:"
            echo "  Ctrl+T     — search files in current dir"
            echo "  Ctrl+R     — fuzzy-search command history"
            echo "  Alt+C      — fuzzy cd into subdirectory"
            echo "  ls | fzf   — pick a file from ls output"
            echo "  ps aux | fzf — pick a process"
            echo "  vim **<Tab>  — fuzzy-find and open file (zsh/bash integration)"
            echo ""
            echo "Key bindings inside fzf:"
            echo "  Ctrl+J/K or Up/Down  — navigate"
            echo "  Enter  — select"
            echo "  Esc    — cancel"
            echo "  Tab    — multi-select"
            echo "  Ctrl+? — toggle preview"
            ;;
        bat)
            echo -e "${YELLOW}bat — Cat with Syntax Highlighting${NC}"
            echo ""
            echo "File viewer with syntax highlighting, Git integration, and line numbers."
            echo ""
            echo "Key flags:"
            echo "  bat file.txt                        View with syntax highlighting"
            echo "  bat -A file.txt                     Show non-printable chars (like cat -A)"
            echo "  bat -n file.txt                     Show line numbers only"
            echo "  bat --style=plain file.txt           Plain (no line numbers/git)"
            echo "  bat -l python file.md               Force language highlighting"
            echo "  bat --list-themes                   List color themes"
            echo "  bat --theme=ansi file.txt            Use specific theme"
            echo ""
            echo "Integrations:"
            echo "  export BAT_THEME='Dracula'          Set theme via env"
            echo "  alias cat='bat --paging=never'      Replace cat with bat"
            ;;
        fd)
            echo -e "${YELLOW}fd — Fast File Find${NC}"
            echo ""
            echo "User-friendly, fast alternative to the 'find' command."
            echo ""
            echo "Key flags:"
            echo "  fd 'pattern'                        Recursive find"
            echo "  fd -e py 'pattern'                  Filter by extension"
            echo "  fd -H 'pattern'                     Include hidden files"
            echo "  fd -t d 'pattern'                   Only directories"
            echo "  fd -t f 'pattern'                   Only files"
            echo "  fd -x chmod +x '{}'                 Execute command on results"
            echo "  fd -E node_modules 'pattern'         Exclude directory"
            echo "  fd --type executable                 Find executables in PATH"
            ;;
        btop)
            echo -e "${YELLOW}btop — Resource Monitor${NC}"
            echo ""
            echo "Modern, colorful system resource monitor with mouse support."
            echo ""
            echo "Key features:"
            echo "  CPU, RAM, disk, network graphs"
            echo "  Process manager — search, filter, kill"
            echo "  GPU monitoring (NVIDIA/AMD)"
            echo "  Config: ~/.config/btop/btop.conf"
            echo ""
            echo "Key bindings:"
            echo "  ?   — Show help"
            echo "  1-4 — Toggle CPU/Net/Proc/Disk panels"
            echo "  Up/Down — Navigate process list"
            echo "  Del/F9 — Kill process"
            echo "  t   — Tree view"
            echo "  Esc — Close panel"
            ;;
        lazygit)
            echo -e "${YELLOW}lazygit — Git TUI${NC}"
            echo ""
            echo "Terminal UI for Git — manage branches, commits, stashes, and conflicts."
            echo ""
            echo "Key bindings:"
            echo "  arrow keys  — navigate"
            echo "  Space       — stage/unstage file"
            echo "  c           — commit (opens editor)"
            echo "  p           — push"
            echo "  P           — pull"
            echo "  d           — diff file"
            echo "  s           — stash"
            echo "  b           — branches"
            echo "  m           — merge"
            echo "  M           — remote management"
            echo "  +           — open in VS Code"
            echo "  :           — execute custom command"
            ;;
        zoxide)
            echo -e "${YELLOW}zoxide — Smarter cd${NC}"
            echo ""
            echo "Learning directory jumper — remembers where you go and jumps there."
            echo ""
            echo "Usage:"
            echo "  z foo     — cd to best match 'foo'"
            echo "  zi foo    — interactive selection (like fzf)"
            echo "  z foo bar — cd to 'foo/bar'"
            echo "  z ~/proj  — literal path also works"
            echo ""
            echo "Install: add 'eval \"\$(zoxide init bash)\"' to ~/.bashrc"
            echo "For zsh: eval \"\$(zoxide init zsh)\""
            echo "For fish: zoxide init fish | source"
            ;;
        delta)
            echo -e "${YELLOW}delta — Git Diff Viewer${NC}"
            echo ""
            echo "Syntax-highlighted git diff pager with side-by-side view and line numbers."
            echo ""
            echo "Setup: add to ~/.gitconfig"
            echo "  [core]"
            echo "      pager = delta"
            echo "  [interactive]"
            echo "      diffFilter = delta --color-only"
            echo "  [delta]"
            echo "      side-by-side = true"
            echo "      line-numbers = true"
            echo "      navigate = true"
            ;;
        tldr)
            echo -e "${YELLOW}tldr — Simplified Man Pages${NC}"
            echo ""
            echo "Community-maintained help pages with practical examples."
            echo ""
            echo "Usage:"
            echo "  tldr tar       — common tar examples"
            echo "  tldr ffmpeg    — ffmpeg usage examples"
            echo "  tldr --update  — update local cache"
            echo "  tldr --list    — list all pages"
            echo ""
            echo "Great for: quick reminders of common flags without reading full man page."
            ;;
        httpie)
            echo -e "${YELLOW}httpie — HTTP Client${NC}"
            echo ""
            echo "Human-friendly curl alternative with JSON support and syntax highlighting."
            echo ""
            echo "Common examples:"
            echo "  http GET https://api.example.com/users"
            echo "  http POST https://api.example.com/users name=John age:=30"
            echo "  http PUT https://api.example.com/users/1 name=Jane"
            echo "  http DELETE https://api.example.com/users/1"
            echo "  http -a user:pass https://api.example.com/protected"
            echo "  https httpbin.org/post hello=world      # shorthand"
            echo "  http --print=HBtb https://example.com    # control output"
            ;;
        glances)
            echo -e "${YELLOW}glances — System Monitoring${NC}"
            echo ""
            echo "Cross-platform system monitor with web UI, client/server mode."
            echo ""
            echo "Usage:"
            echo "  glances              — full-screen monitor"
            echo "  glances -w           — start web UI (http://localhost:61208)"
            echo "  glances -s           — server mode"
            echo "  glances -c <host>    — connect to remote server"
            echo "  glances -t 5         — refresh every 5 seconds"
            echo "  glances --export csv — export to CSV"
            ;;
        thefuck)
            echo -e "${YELLOW}thefuck — Command Correction${NC}"
            echo ""
            echo "Corrects mistyped console commands by suggesting fixes."
            echo ""
            echo "Usage:"
            echo "  $ apt-get install vim"
            echo "  E: Could not open lock file"
            echo "  $ fuck"
            echo "  sudo apt-get install vim  [enter/up/ctrl-c]"
            echo ""
            echo "Alias: add 'eval \"\$(thefuck --alias)\"' to shell config"
            echo "Rarely needed, but indispensable when you do."
            ;;
        eza)
            echo -e "${YELLOW}eza — Modern ls${NC}"
            echo ""
            echo "Modern replacement for ls with icons, colors, and tree view."
            echo ""
            echo "Key flags:"
            echo "  eza -l                     — long format (permissions, size, date)"
            echo "  eza -la                    — include hidden files"
            echo "  eza --tree                 — tree view"
            echo "  eza --icons                — file type icons"
            echo "  eza --group-directories-first"
            echo "  eza --sort=size            — sort by size"
            echo "  eza --git                  — show git status per file"
            echo "  eza -l --header            — show column headers"
            ;;
        dust)
            echo -e "${YELLOW}dust — Disk Usage Visualizer${NC}"
            echo ""
            echo "More intuitive du — shows disk usage with bar charts."
            echo ""
            echo "Key flags:"
            echo "  dust                      — current dir"
            echo "  dust /path                — specific path"
            echo "  dust -d 3                 — depth 3"
            echo "  dust -s                   — only files (apparent size)"
            echo "  dust -X '*.pyc'           — exclude patterns"
            echo "  dust -b                   — bytes (not human-readable)"
            echo "  dust -r                   — reverse sort"
            ;;

        # ──────────────────────────────────────────────────────────────
        # DEV TOOLS (GUI)
        # ──────────────────────────────────────────────────────────────
        Flameshot)
            echo -e "${YELLOW}Flameshot${NC}"
            echo ""
            echo "Feature-rich screenshot tool with built-in editor and annotations."
            echo ""
            echo "Tips:"
            echo "  • Launch: flameshot gui to take a screenshot"
            echo "  • Editor: arrows, boxes, circles, blur, text annotations"
            echo "  • Upload to Imgur directly from the editor"
            echo "  • Configurable keyboard shortcuts"
            echo "  • Can run as daemon for quick screenshots: flameshot &"
            ;;
        KeePassXC)
            echo -e "${YELLOW}KeePassXC${NC}"
            echo ""
            echo "Cross-platform password manager with local database storage."
            echo ""
            echo "Tips:"
            echo "  • Database stays on your machine — no cloud dependency"
            echo "  • Browser integration via KeePassXC-Browser extension"
            echo "  • Built-in password generator with strength meter"
            echo "  • Supports TOTP (2FA codes) in-app"
            echo "  • Auto-type: fill credentials into any app/window"
            echo "  • Export/import from other password managers"
            ;;
        mpv)
            echo -e "${YELLOW}mpv — Minimalist Video Player${NC}"
            echo ""
            echo "Lightweight, powerful video player with minimal GUI and scriptable controls."
            echo ""
            echo "Key flags:"
            echo "  mpv video.mp4              Play video"
            echo "  mpv --shuffle *.mp4        Playlist, shuffled"
            echo "  mpv --loop video.mp4       Loop"
            echo "  mpv --speed=1.5 video.mp4  Play at 1.5x"
            echo "  mpv --vo=gpu --hwdec=vaapi video.mp4  GPU-accelerated"
            echo "  mpv --screenshot-format=png video.mp4  Screenshot format"
            echo ""
            echo "Keybindings:"
            echo "  9/0   — volume"
            echo "  [/]   — speed -/+ 0.1x"
            echo "  f     — fullscreen"
            echo "  s/S   — screenshot (video/window)"
            echo "  q     — quit"
            ;;
        Syncthing)
            echo -e "${YELLOW}Syncthing${NC}"
            echo ""
            echo "Peer-to-peer continuous file synchronization between devices."
            echo ""
            echo "Tips:"
            echo "  • No cloud server — your data stays between your devices"
            echo "  • Web UI: http://localhost:8384"
            echo "  • Encrypted transfer (TLS) and relay fallback if devices can't connect"
            echo "  • Versioning: keep deleted/changed files in trash"
            echo "  • Selective sync: choose which folders to sync per device"
            echo "  • Runs as a service: systemctl --user start syncthing"
            ;;
        VLC)
            echo -e "${YELLOW}VLC Media Player${NC}"
            echo ""
            echo "Versatile media player that plays almost anything (files, discs, streams)."
            echo ""
            echo "Tips:"
            echo "  • Plays almost any format without codec packs"
            echo "  • Network stream: Media → Open Network Stream (or Ctrl+N)"
            echo "  • Convert media: Media → Convert/Save"
            echo "  • Take snapshots: Video → Take Snapshot (or Shift+S)"
            echo "  • Speed control: [ and ] keys"
            echo "  • Equalizer: Tools → Effects and Filters → Equalizer"
            echo "  • Loop A→B: View → Advanced Controls, then use A/B buttons"
            ;;

        # ──────────────────────────────────────────────────────────────
        # LANGUAGES
        # ──────────────────────────────────────────────────────────────
        Python)
            echo -e "${YELLOW}Python${NC}"
            echo ""
            echo "High-level, interpreted language — great for scripting, data science, web, AI."
            echo ""
            echo "Usage:"
            echo "  python3 script.py      Run script"
            echo "  python3 -m venv venv   Create virtual environment"
            echo "  python3 -m pip install <pkg>  Install package"
            echo "  python3 -c 'print(1+1)'  One-liner"
            echo "  python3 -m http.server  Simple HTTP server"
            echo "  python3 -m pdb script.py  Debug with pdb"
            ;;
        "Node.js")
            echo -e "${YELLOW}Node.js${NC}"
            echo ""
            echo "JavaScript runtime built on V8 — for server-side JS and tooling."
            echo ""
            echo "Usage:"
            echo "  node script.js         Run script"
            echo "  node -e 'console.log(1+1)'  One-liner"
            echo "  node --inspect script.js    Debug with Chrome DevTools"
            echo "  node -r dotenv/config script.js  Pre-load modules"
            echo ""
            echo "npm commands:"
            echo "  npm init -y            Init project"
            echo "  npm install <pkg>      Install package"
            echo "  npm run <script>       Run package.json script"
            echo "  npx <pkg>              Run without installing"
            ;;
        TypeScript)
            echo -e "${YELLOW}TypeScript${NC}"
            echo ""
            echo "JavaScript with types — compiles to plain JS, catches errors at compile time."
            echo ""
            echo "Usage:"
            echo "  tsc script.ts          Compile to JS"
            echo "  tsc --init             Create tsconfig.json"
            echo "  tsc --watch            Watch mode (recompile on change)"
            echo "  npx ts-node script.ts  Run directly (without compile step)"
            echo "  npx tsc --noEmit       Type-check without output"
            ;;
        Go)
            echo -e "${YELLOW}Go (Golang)${NC}"
            echo ""
            echo "Compiled, concurrent language by Google — fast builds, great for CLIs/servers."
            echo ""
            echo "Usage:"
            echo "  go run main.go         Run directly"
            echo "  go build .             Build binary"
            echo "  go install .           Build and install to \$GOPATH/bin"
            echo "  go test ./...          Run all tests"
            echo "  go fmt ./...           Format all code"
            echo "  go mod init <module>   Init new module"
            echo "  go get <pkg>           Add dependency"
            echo "  go vet ./...           Static analysis"
            ;;
        Rust)
            echo -e "${YELLOW}Rust${NC}"
            echo ""
            echo "Systems language focused on safety, speed, and concurrency — no garbage collector."
            echo ""
            echo "Usage:"
            echo "  cargo new myproject    Init new project"
            echo "  cargo build            Build (debug)"
            echo "  cargo build --release  Build (optimized)"
            echo "  cargo run              Build and run"
            echo "  cargo test             Run tests"
            echo "  cargo check            Type-check (fast)"
            echo "  cargo fmt              Format code"
            echo "  cargo clippy           Lint"
            echo "  cargo add <dep>        Add dependency"
            echo "  rustc main.rs          Compile directly"
            ;;
        "Java (OpenJDK)")
            echo -e "${YELLOW}Java (OpenJDK)${NC}"
            echo ""
            echo "Mature, JVM-based language — enterprise, Android, big data."
            echo ""
            echo "Usage:"
            echo "  javac Main.java        Compile"
            echo "  java Main              Run"
            echo "  java -jar app.jar      Run JAR"
            echo "  java --version         Check version"
            echo "  jshell                 Interactive REPL"
            ;;
        "C/C++ (GCC)")
            echo -e "${YELLOW}C/C++ (GCC)${NC}"
            echo ""
            echo "Foundational compiled languages — systems programming, embedded, performance-critical."
            echo ""
            echo "Usage:"
            echo "  gcc program.c -o prog      Compile C"
            echo "  g++ program.cpp -o prog    Compile C++"
            echo "  gcc -Wall -Wextra -o prog prog.c  With warnings"
            echo "  gcc -O2 -o prog prog.c     Optimized build"
            echo "  gcc -g -o prog prog.c      Debug build"
            echo "  make                       Use Makefile"
            echo "  gcc -I./include -L./lib -lmylib prog.c -o prog  Link library"
            ;;
        "C# (.NET)")
            echo -e "${YELLOW}C# (.NET)${NC}"
            echo ""
            echo "Microsoft's language — modern, cross-platform via .NET Core."
            echo ""
            echo "Usage:"
            echo "  dotnet new console -n myapp    Create console app"
            echo "  dotnet new webapi -n myapi     Create web API"
            echo "  dotnet build                   Build"
            echo "  dotnet run                     Run"
            echo "  dotnet test                    Run tests"
            echo "  dotnet add package <pkg>       Add NuGet package"
            echo "  dotnet publish -c Release      Publish for deployment"
            ;;
        Ruby)
            echo -e "${YELLOW}Ruby${NC}"
            echo ""
            echo "Elegant, dynamic language — great for web apps (Rails), scripting, and automation."
            echo ""
            echo "Usage:"
            echo "  ruby script.rb           Run script"
            echo "  ruby -e 'puts 1+1'      One-liner"
            echo "  irb                      Interactive REPL"
            echo "  gem install <gem>        Install Ruby gem"
            echo "  bundle init              Init Bundler project"
            echo "  bundle exec ruby app.rb  Run with Gemfile deps"
            ;;
        PHP)
            echo -e "${YELLOW}PHP${NC}"
            echo ""
            echo "Server-side scripting language — powers most of the web (WordPress, Laravel)."
            echo ""
            echo "Usage:"
            echo "  php script.php          Run script"
            echo "  php -a                  Interactive shell"
            echo "  php -S localhost:8000   Built-in dev server"
            echo "  php -m                  List loaded modules"
            echo "  composer install        Install PHP dependencies"
            ;;
        Lua)
            echo -e "${YELLOW}Lua${NC}"
            echo ""
            echo "Lightweight, embeddable scripting language — used in games, Neovim, Redis."
            echo ""
            echo "Usage:"
            echo "  lua script.lua          Run script"
            echo "  lua -i script.lua       Run then enter interactive mode"
            echo "  luac -o out.luac script.lua  Compile to bytecode"
            echo "  lua -e 'print(1+1)'     One-liner"
            ;;
        R)
            echo -e "${YELLOW}R${NC}"
            echo ""
            echo "Language for statistical computing, data analysis, and visualization."
            echo ""
            echo "Usage:"
            echo "  R                       Start REPL"
            echo "  Rscript script.R        Run script"
            echo "  R -e 'summary(data)'    One-liner"
            echo "  install.packages('ggplot2')  Install package"
            ;;
        Zig)
            echo -e "${YELLOW}Zig${NC}"
            echo ""
            echo "Modern systems language — aims to be a better C with cross-compilation baked in."
            echo ""
            echo "Usage:"
            echo "  zig run main.zig        Run directly"
            echo "  zig build-exe main.zig  Build executable"
            echo "  zig build               Build project (build.zig)"
            echo "  zig test src/main.zig   Run tests"
            echo "  zig fmt .               Format code"
            echo "  zig translate-c foo.h   Generate Zig bindings from C headers"
            ;;
        Dart)
            echo -e "${YELLOW}Dart${NC}"
            echo ""
            echo "Language by Google — used for Flutter mobile/web/desktop apps."
            echo ""
            echo "Usage:"
            echo "  dart run main.dart      Run script"
            echo "  dart compile exe main.dart  Build standalone binary"
            echo "  dart analyze            Static analysis"
            echo "  dart format .           Format code"
            echo "  dart test               Run tests"
            echo "  flutter create myapp    Create Flutter project"
            ;;
        Kotlin)
            echo -e "${YELLOW}Kotlin${NC}"
            echo ""
            echo "Modern JVM language by JetBrains — official Android language, also server-side."
            echo ""
            echo "Usage:"
            echo "  kotlinc main.kt -include-runtime -d main.jar  Compile to JAR"
            echo "  java -jar main.jar       Run JAR"
            echo "  kotlin -e 'println(1+1)'  One-liner"
            echo "  kotlinc-jvm              REPL"
            ;;

        *)
            echo "No explanation available for '$tool_name'."
            ;;
    esac

    echo -e "${CYAN}═══════════════════════════════════════════════════════════════${NC}"
    echo ""
}

_explain_by_index() {
    local -n list="$1"
    local idx="$2"
    local i=1
    for info in "${list[@]}"; do
        if [ "$i" -eq "$idx" ]; then
            local name="${info%%|*}"
            _explain_tool "$name"
            return
        fi
        ((i++))
    done
    log_message "WARN" "Invalid tool index: $idx"
}
